# generate diagnostic plots
print(dir())
# load('preloaded_retinas_381_752_753.rdata')
require(retina)
# reef_path <- system.file(package = "retina", 'inst/extdata')
# reef_path <- paste0(reef_path, "reef_fish.rdata")
# load(reef_path)
message("Imported processed data")
message("Preparing for Thin Plate Spline Fit Plots")
fit_plots(Pmol_752$fit_data1)
fit_plots(Pmol_753$fit_data1)
fit_plots(Ntae_381$fit_data1)
dev.off()
